language: java

dist: trusty
sudo: false
install: true

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 10 "Oracle JDK"
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: test
      script:
        - echo PATH = ${PATH}
        - echo JAVA_HOME = ${JAVA_HOME}
        - java -version
        - ./gradlew --version
        - ./gradlew test
    - stage: snapshot
      env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
      script:
        - ./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: snapshot
      env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
      script:
        - ./gradlew artifactoryPublish -x test -Dsnapshot=false -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER