language: java

dist: trusty
sudo: false

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 10 "Oracle JDK"
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
# Java 10 "OpenJDK"
    - env: JDK='OpenJDK 10'
      install: . ./install-jdk.sh -F 10 -L GPL

jobs:
  include:
    - script:
      - ./gradlew --version
      - ./gradlew test
    - if: branch = master
      - ./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - if: branch = release
      - ./gradlew artifactoryPublish -x test -Dsnapshot=false -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
