sudo: false
dist: trusty
language: java

matrix:
  include:
    - jdk: oraclejdk10
    - jdk: oraclejdk11

stages:
  - name: build
  - name: snapshot
    if: branch = master
  - name: release
    if: branch = release

jobs:
  include:
    - stage: build
      jdk: oraclejdk10
      script:
        - echo PATH = ${PATH}
        - echo JAVA_HOME = ${JAVA_HOME}
        - java -version
        - ./gradlew --version
        - ./gradlew test
    - stage: snapshot
      jdk: oraclejdk10
      script:
        - ./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: snapshot
      jdk: oraclejdk10
      script:
        - ./gradlew artifactoryPublish -x test -Dsnapshot=false -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER